<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="EDS 241 / ESM 244 (DUE: 2/4/26)">
<meta name="dcterms.date" content="2026-01-26">

<title>🌬️🗳 Assignment 2: Wind Turbines, Matching, and Difference-in-Differences</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="HW2_START_files/libs/clipboard/clipboard.min.js"></script>
<script src="HW2_START_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="HW2_START_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="HW2_START_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="HW2_START_files/libs/quarto-html/popper.min.js"></script>
<script src="HW2_START_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="HW2_START_files/libs/quarto-html/anchor.min.js"></script>
<link href="HW2_START_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="HW2_START_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="HW2_START_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="HW2_START_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="HW2_START_files/libs/bootstrap/bootstrap-aff6bd71cf38ce7a6494770b00151a6f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">🌬️🗳 Assignment 2: Wind Turbines, Matching, and Difference-in-Differences</h1>
<p class="subtitle lead">Replicate causal inference identification strategies in Stokes (2015)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>EDS 241 / ESM 244 (DUE: 2/4/26) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 26, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="assignment-instructions" class="level3">
<h3 class="anchored" data-anchor-id="assignment-instructions">Assignment instructions</h3>
<p>Working with classmates to troubleshoot code and concepts is encouraged. If you collaborate, list collaborators at the top of your submission.</p>
<p>All written responses must be written independently (in your own words).</p>
<p>Keep your work readable: Use clear headings and label plot elements thoughtfully.</p>
<p>Assignment submission : Richard Montes Lemus</p>
<hr>
</section>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>In this assignment you will be doing political weather forecasting except the “storms” we care about are electoral swings that might follow local wind turbine development.</p>
<p>In Stokes (2015), the idea is that a policy with diffuse benefits (cleaner electricity) can create concentrated local costs (turbines nearby), and those local opponents may “send a signal” at the ballot box (i.e., NIMBYISM). Your job is to use two statistical tools:</p>
<ul>
<li>Matching: Can we create a more apples-to-apples comparison between precincts that did vs.&nbsp;did not end up near turbine proposals?</li>
<li>Fixed effects + Difference-in-Differences: Can we use repeated elections to estimate how within-precinct changes in turbine exposure relate to changes in incumbent vote share?</li>
</ul>
<hr>
</section>
<section id="learning-goal-replicate-the-matching-and-fixed-effects-analyses-from-study" class="level3">
<h3 class="anchored" data-anchor-id="learning-goal-replicate-the-matching-and-fixed-effects-analyses-from-study">Learning goal: Replicate the matching and fixed effects analyses from study:</h3>
<blockquote class="blockquote">
<p>Stokes (2015): <em>“Electoral Backlash against Climate Policy: A Natural Experiment on Retrospective Voting and Local Resistance to Public Policy</em>.</p>
</blockquote>
<ul>
<li><strong>Study:</strong> <a href="https://drive.google.com/file/d/1y2Okzjq2EA43AW5JzCvFS8ecLpeP6NKh/view?usp=sharing">Stokes (2015) - Article</a></li>
<li><strong>Data source:</strong> <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/SDUGCC">Dataverse-Stokes2015</a></li>
</ul>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><code>NOTE:</code> Replication of study estimates will be approximate. An alternative matching procedure and fixed effects estimation package are utilized in this assignment for illustration purposes.</p>
</div>
</div>
</div>
<hr>
</section>
<section id="setup-load-libraries" class="level3">
<h3 class="anchored" data-anchor-id="setup-load-libraries">Setup: Load libraries</h3>
<ol start="0" type="1">
<li>Load libraries (+ install if needed)</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MatchIt) <span class="co"># matching</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cobalt)  <span class="co"># balance + love plots</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest) <span class="co"># fast fixed effects</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales) <span class="co"># plotting</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<hr>
</section>
<section id="part-1-study-background" class="level3">
<h3 class="anchored" data-anchor-id="part-1-study-background">Part 1: Study Background</h3>
<section id="a.-dive-into-the-details-of-the-study-design-and-evaluation-plan" class="level4">
<h4 class="anchored" data-anchor-id="a.-dive-into-the-details-of-the-study-design-and-evaluation-plan"><strong>1A.</strong> Dive into the details of the study design and evaluation plan</h4>
<blockquote class="blockquote">
<p>Goal: Get familiar with the study setting, environmental issue, and policy under evaluation.</p>
</blockquote>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><code>NOTE:</code> Read over study to inform your response to the assignment questions. For this assignment we will skip-over sections that describe the <em>Instrumental Variables</em> identification strategy. We will cover instrumental variable designs weeks 6-7.</p>
</div>
</div>
</div>
<p><strong>1A.Q1</strong> Summarize the environmental policy issue, the outcome of interest, and the intervention being evaluated. Be sure to include a brief description of each of the following key elements of the study: unit of analysis, outcome, treatment, comparison group):</p>
<p><em>Response:</em> _________________________</p>
<p>Environmental Policy Issue:</p>
<p>In 2009, the Liberal government in Ontario Canada passed the Green Energy Act. This allows private corporations to build clean wind energy infrastructure without needing approval from local communities. Although a majority of people in Ontario supported clean energy, there were concentrated costs for local communities close to these projects. These communities sent a signal of disapproval by causing the Liberal government to lose seats at the upcoming election. This caused the government to hold back from building these projects.</p>
<p>Outcome of Interest:</p>
<p>The outcome of interest is Liberal party vote share in provincial elections.</p>
<p>Intervention Being Evaluated:</p>
<p>The intervention being evaluated is placing or proposing wind turbine projects in or near precincts.</p>
<p>Unit of Analysis:</p>
<p>Electoral precincts in the Ontario</p>
<p>Outcome treatment:</p>
<p>Precincts with proposed or built wind turbines.</p>
<p>Comparison group:</p>
<p>Precincts without proposed or built wind turbines</p>
<p><strong>1A.Q2</strong> Why might turbine proposals be correlated with baseline political preferences or rural areas? Provide 2 plausible mechanisms, and explain why that creates confounding.</p>
<p><em>Response:</em> _________________________</p>
<p>Since wind turbines could only be built in rural areas this causes a confound. People who live in rural areas tend to be more conservative and might already plan to vote against policies commonly associated with liberal parties. Therefore, loss of liberal party voter share may be due to pre-existing trends in these rural areas that were already becoming more anti-liberal in the first place. This decline in liberal votes may be wrongly attributed to the wind turbine project when it’s actually a pre-existing political ideology trend.</p>
<p>Another confound would be that when wealthy developers were thinking about where to place these wind turbines, they purposely avoided wealthy and politically active communities. They might have anticipated these communities would protest and slow down the development project and decided to instead choose lower income and less politically active communities. This may mean the disapproval expressed through voting against the Liberal Party might not be caused by the turbines themselves, but rather reflects pre-existing characteristics of communities that got turbines.</p>
<hr>
</section>
<section id="b.-break-down-the-causal-inference-strategy-and-identify-threats-to-identification" class="level4">
<h4 class="anchored" data-anchor-id="b.-break-down-the-causal-inference-strategy-and-identify-threats-to-identification"><strong>1B.</strong> Break down the causal inference strategy and identify threats to identification:</h4>
<p><strong>1B.Q1</strong> What is the key identifying assumption for a fixed effects / Difference-in-Difference design? Explain how this assumption when satisfied provides evidence of causal effect:</p>
<p><em>Response:</em> _________________________</p>
<p>The key identifying assumption is that in the absence of treatment, the treated and control group would have experienced parallel trends over time. If both groups experienced the same trend in the absence of treatment, this indicated the treatment is responsible for the change in slope for the treated group and provides evidence of causal effect if the slope change is significant.</p>
<p><strong>1B.Q2</strong> What is the reason for using a fixed effects approach from a causal inference perspective? Summarize within the context of study (in your own words).</p>
<p><em>Response:</em> _________________________</p>
<p>With a fixed effects approach we compare each precinct directly to itself over time and observe changes that same precinct experiences over time. This allows us to control for time-invariant differences that are bound to exists between different precincts in our study.</p>
<p><strong>1B.Q3</strong> What part of the SUTVA assumption is most likely violated in the context of this study design (and why)?</p>
<p><em>Response:</em> _________________________</p>
<p>The SUTVA assumption requiring one unit’s treatment to not affect the outcome of another unit is being violated. When a turbine is placed in one precinct it doesn’t necessarily only affect that specific precinct. The fossil fuel job displacement caused by a wind turbine may affect many surrounding precinct workers since they are most likely spread out across various precincts. Furthermore, the mobilization efforts against wind turbines might not be contained to the precincts containing wind turbines, they may inspire allies from other precincts without wind turbines to vote in their favor.</p>
<p><strong>1B.Q4</strong> Why does spillover matter when estimating an unbiased treatment effect?</p>
<p><em>Response:</em> _________________________</p>
<p>Spillover could cause the difference between between control and treated groups to seem smaller than they really are. This is because the control group could potentially vote similarly to the treatment group due to it being influenced by the treatment group - this could introduce bias.</p>
<p><strong>1B.Q5</strong> How do the authors assess the risk of spillovers, and what analytic choice do they make to attempt to mitigate the risk that spillover biases the causal estimate?</p>
<p><em>Response:</em> _________________________</p>
<p>The authors assess the risk of spillover by testing for the statistical significance of the treatment for precincts within a 1km, 2km, 3km, 4km, and 5km radius from a wind turbine. They see a statistically significant voter decline in precincts that are 0-3km from the wind turbine and choose to assign precincts within a 3km buffer from a wind turbine to the treated group as opposed to just assigning precincts containing wind turbines to the treated group.</p>
<hr>
</section>
</section>
<section id="part-2-matching" class="level3">
<h3 class="anchored" data-anchor-id="part-2-matching">Part 2: Matching</h3>
<hr>
<p>We will start by evaluating the 2007 survey (cross-sectional) data. Treatment is defined by whether a precinct is near a turbine proposal (within 3 km).</p>
<blockquote class="blockquote">
<p>Goal: Match precincts using pre-treatment covariates and then estimate the effect of proposed wind turbines on incumbent vote share.</p>
</blockquote>
<section id="a.-load-data-for-matching" class="level4">
<h4 class="anchored" data-anchor-id="a.-load-data-for-matching"><strong>2A.</strong> Load data for matching</h4>
<ol type="1">
<li>Read in data file <code>stokes15_survey2007.csv</code></li>
<li>Code <code>precinct_id</code> and <code>district_id</code> as factors</li>
<li>Take a look at the data</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>match_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"stokes15_survey2007.csv"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">precinct_id =</span> <span class="fu">as.factor</span>(precinct_id),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">district_id =</span> <span class="fu">as.factor</span>(district_id))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>2A.Q1</strong> Intuition check: <strong>Why match?</strong> Explain rationale for using this method.</p>
<p><em>Response:</em> _________________________</p>
<p>We should match so that we make sure our treated precinct’s counter factual is as similar as possible for pre-treatment variables. This makes sure the difference we see between affected and unaffected precincts is due to the wind turbine construction and not some pre-existing differences in variables between them.</p>
<hr>
</section>
<section id="b.-check-imbalance-before-matching" class="level4">
<h4 class="anchored" data-anchor-id="b.-check-imbalance-before-matching"><strong>2B.</strong> Check imbalance (before matching)</h4>
<ul>
<li>Create a covariate <em>balance table</em> comparing treated and control precincts</li>
<li>Treatment indicator: <code>proposed_turbine_3km</code></li>
<li>Include pre-treatment covariates: <code>log_home_val_07</code>, <code>p_uni_degree</code>, <code>log_median_inc</code>, <code>log_pop_denc</code></li>
<li>Use the <code>tbl_summary()</code> function from the <code>{gtsummary}</code> package.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>match_data <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    proposed_turbine_3km, </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    log_home_val_07,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    p_uni_degree,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    log_median_inc,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    log_pop_denc) <span class="sc">%&gt;%</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tbl_summary</span>(</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> proposed_turbine_3km,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">statistic =</span> <span class="fu">list</span>(</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>      <span class="fu">all_continuous</span>() <span class="sc">~</span> <span class="st">"{mean} ({sd})"</span>,</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">all_categorical</span>() <span class="sc">~</span> <span class="st">"{n} ({p}%)"</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">modify_header</span>(label <span class="sc">~</span> <span class="st">"**Covariate**"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">modify_spanning_header</span>(<span class="fu">c</span>(<span class="st">"stat_1"</span>, <span class="st">"stat_2"</span>) <span class="sc">~</span> <span class="st">"**Near Turbine**"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="nudripjbbg" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#nudripjbbg table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#nudripjbbg thead, #nudripjbbg tbody, #nudripjbbg tfoot, #nudripjbbg tr, #nudripjbbg td, #nudripjbbg th {
  border-style: none;
}

#nudripjbbg p {
  margin: 0;
  padding: 0;
}

#nudripjbbg .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#nudripjbbg .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#nudripjbbg .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#nudripjbbg .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#nudripjbbg .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#nudripjbbg .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nudripjbbg .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#nudripjbbg .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#nudripjbbg .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#nudripjbbg .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#nudripjbbg .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#nudripjbbg .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#nudripjbbg .gt_spanner_row {
  border-bottom-style: hidden;
}

#nudripjbbg .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#nudripjbbg .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#nudripjbbg .gt_from_md > :first-child {
  margin-top: 0;
}

#nudripjbbg .gt_from_md > :last-child {
  margin-bottom: 0;
}

#nudripjbbg .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#nudripjbbg .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#nudripjbbg .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#nudripjbbg .gt_row_group_first td {
  border-top-width: 2px;
}

#nudripjbbg .gt_row_group_first th {
  border-top-width: 2px;
}

#nudripjbbg .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#nudripjbbg .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#nudripjbbg .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#nudripjbbg .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nudripjbbg .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#nudripjbbg .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#nudripjbbg .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#nudripjbbg .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#nudripjbbg .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nudripjbbg .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#nudripjbbg .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#nudripjbbg .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#nudripjbbg .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#nudripjbbg .gt_left {
  text-align: left;
}

#nudripjbbg .gt_center {
  text-align: center;
}

#nudripjbbg .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#nudripjbbg .gt_font_normal {
  font-weight: normal;
}

#nudripjbbg .gt_font_bold {
  font-weight: bold;
}

#nudripjbbg .gt_font_italic {
  font-style: italic;
}

#nudripjbbg .gt_super {
  font-size: 65%;
}

#nudripjbbg .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#nudripjbbg .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#nudripjbbg .gt_indent_1 {
  text-indent: 5px;
}

#nudripjbbg .gt_indent_2 {
  text-indent: 10px;
}

#nudripjbbg .gt_indent_3 {
  text-indent: 15px;
}

#nudripjbbg .gt_indent_4 {
  text-indent: 20px;
}

#nudripjbbg .gt_indent_5 {
  text-indent: 25px;
}

#nudripjbbg .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#nudripjbbg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="gt_col_headings gt_spanner_row header">
<th rowspan="2" id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Covariate</strong></th>
<th colspan="2" id="level 1; stat_1" class="gt_center gt_columns_top_border gt_column_spanner_outer" data-quarto-table-cell-role="th" scope="colgroup"><div class="gt_column_spanner">
<strong>Near Turbine</strong>
</div></th>
</tr>
<tr class="gt_col_headings even">
<th id="stat_1" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>0</strong><br>
N = 5,619<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="stat_2" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>1</strong><br>
N = 354<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">log_home_val_07</td>
<td class="gt_row gt_center" headers="stat_1">12.26 (0.37)</td>
<td class="gt_row gt_center" headers="stat_2">12.29 (0.29)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">p_uni_degree</td>
<td class="gt_row gt_center" headers="stat_1">0.17 (0.12)</td>
<td class="gt_row gt_center" headers="stat_2">0.13 (0.09)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">log_median_inc</td>
<td class="gt_row gt_center" headers="stat_1">10.32 (0.22)</td>
<td class="gt_row gt_center" headers="stat_2">10.31 (0.19)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">log_pop_denc</td>
<td class="gt_row gt_center" headers="stat_1">5.12 (2.40)</td>
<td class="gt_row gt_center" headers="stat_2">3.54 (1.78)</td>
</tr>
</tbody><tfoot>
<tr class="gt_footnotes odd">
<td colspan="3" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> Mean (SD)</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
<p><strong>2B.Q1</strong> Summarize the table output: Which covariates look balanced/imbalanced?</p>
<p><em>Response:</em> _________________________</p>
<p>For my control and treatment groups, the log_home_val_07 and log_median_inc variables seem to be pretty balanced, the p_uni_degree variable difference is moderate, and the log_pop_denc variable is severely unbalanced.</p>
<p><strong>2B.Q2</strong> Describe in your own words why these covariates might be expected to confound the treatment estimate:</p>
<p><em>Response (2-4 sentences):</em> _________________________</p>
<p>The proportion with university degrees (<code>p_uni_degree</code>) and population density (<code>log_pop_denc</code>) could both confound the treatment estimate because they’re associated with political preferences. Precincts with higher proportions of university graduates tend to vote more liberal, while rural precincts with a lower population density tend to vote less liberal. This could mean the differences we see between our control and treatment group is due to these pre-existing differences and not necessarily wind turbines.</p>
<hr>
<p><strong>2B.Q3</strong> Intuition check: What type of data do you need to conduct a matching analysis?</p>
<p><em>Response:</em> _________________________</p>
<p>You need to have a lot of pre-treatment covariates and a lot of control data relative to treated data.</p>
<hr>
</section>
</section>
<section id="conduct-matching-estimation-using-the-matchit-package" class="level3">
<h3 class="anchored" data-anchor-id="conduct-matching-estimation-using-the-matchit-package">Conduct matching estimation using the {<code>MatchIt</code>} package:</h3>
<p>📜 <a href="https://kosukeimai.github.io/MatchIt/">Documentation - MatchIt</a></p>
<p>Learning goals:</p>
<ul>
<li>Approximate the Mahalanobis matching method used in Stokes (2015)</li>
<li>Implement another common matching approach called <code>propensity score matching</code></li>
</ul>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><code>NOTE</code>: In the replication code associated with Stokes (2015) the {<code>AER</code>} package is used for Mahalanobis matching. In this assignment we use the {<code>MatchIt</code>} package. The results are comparable but will not be exactly the same.</p>
</div>
</div>
</div>
<hr>
</section>
<section id="c.-mahalanobis-nearest-neighbor-matching" class="level3">
<h3 class="anchored" data-anchor-id="c.-mahalanobis-nearest-neighbor-matching">2C. Mahalanobis nearest-neighbor matching</h3>
<ul>
<li>Conduct Mahalanobis matching<br>
</li>
<li>Use nearest-neighbor match without replacement using Mahalanobis distance</li>
<li>Use 1-to-1 matching (match one control unit to each treatment unit)</li>
<li>Extract the matched data using <code>match.data()</code></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2412026</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>match_model <span class="ot">&lt;-</span> <span class="fu">matchit</span>(proposed_turbine_3km <span class="sc">~</span> log_home_val_07 <span class="sc">+</span> </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    p_uni_degree <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    log_median_inc <span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    log_pop_denc,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> match_data, </span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"nearest"</span>,       <span class="co"># Nearest neighbor matching</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">distance =</span> <span class="st">"mahalanobis"</span>, <span class="co"># Mahalanobis distance</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">ratio =</span> <span class="dv">1</span>,                <span class="co"># Match one control unit to one treatment unit (1:1 matching)</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">replace =</span> <span class="cn">FALSE</span>           <span class="co"># Control observations are not replaced</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract matched data</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>matched_data <span class="ot">&lt;-</span> <span class="fu">match.data</span>(match_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(match_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
matchit(formula = proposed_turbine_3km ~ log_home_val_07 + p_uni_degree + 
    log_median_inc + log_pop_denc, data = match_data, method = "nearest", 
    distance = "mahalanobis", replace = FALSE, ratio = 1)

Summary of Balance for All Data:
                Means Treated Means Control Std. Mean Diff. Var. Ratio
log_home_val_07       12.2948       12.2620          0.1138     0.5941
p_uni_degree           0.1257        0.1688         -0.5032     0.4916
log_median_inc        10.3096       10.3219         -0.0636     0.7581
log_pop_denc           3.5398        5.1192         -0.8897     0.5474
                eCDF Mean eCDF Max
log_home_val_07    0.0382   0.0881
p_uni_degree       0.1032   0.1769
log_median_inc     0.0355   0.0750
log_pop_denc       0.2099   0.3713

Summary of Balance for Matched Data:
                Means Treated Means Control Std. Mean Diff. Var. Ratio
log_home_val_07       12.2948       12.2975         -0.0093     1.0063
p_uni_degree           0.1257        0.1262         -0.0060     1.0485
log_median_inc        10.3096       10.3096          0.0002     1.0403
log_pop_denc           3.5398        3.5982         -0.0329     0.9784
                eCDF Mean eCDF Max Std. Pair Dist.
log_home_val_07    0.0075   0.0282          0.1334
p_uni_degree       0.0088   0.0367          0.1642
log_median_inc     0.0073   0.0395          0.1225
log_pop_denc       0.0109   0.0508          0.1485

Sample Sizes:
          Control Treated
All          5619     354
Matched       354     354
Unmatched    5265       0
Discarded       0       0</code></pre>
</div>
</div>
<p><strong>2C.Q1</strong> Using the <code>summary()</code> output: Which covariate had the largest and smallest <code>Std. Mean Diff.</code> before matching. Next, compare largest/smallest <code>Std. Mean Diff.</code> after matching.</p>
<p><em>Response:</em> _________________________</p>
<hr>
<p>Largest Std. Meal Diff Before Matching</p>
<ul>
<li>log_pop_denc</li>
</ul>
<p>Smallest Std. Meal Diff Before Matching</p>
<ul>
<li>log_median_inc</li>
</ul>
<p>After matching log_pop_denc still has the largest Std but it is much smaller (-0.8897 vs -0.0329). log_median_inc still has the smallest Std but is even smaller (-0.0636 vs 0.0002) - we now see a near perfect match for this variable.</p>
<section id="d.-create-a-love-plot-using-love.plot" class="level4">
<h4 class="anchored" data-anchor-id="d.-create-a-love-plot-using-love.plot">2D. Create a “love plot” using <code>love.plot()</code> ❤️</h4>
<p>📜 <a href="https://ngreifer.github.io/cobalt/">Documentation - cobalt</a></p>
<ul>
<li>Plot mean differences for data before &amp; after matching across all pre-treatment covariates</li>
<li>This is an effective way to evaluate how effective matching was at achieving balance.</li>
</ul>
<hr>
<ul>
<li>Make a love plot of standardized mean differences (SMDs) before vs after matching.</li>
<li>Include a threshold line at 0.1.</li>
<li>In love plot display <code>mean.diffs</code></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>new_names <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">old =</span> <span class="fu">c</span>(<span class="st">"log_home_val_07"</span>, <span class="st">"p_uni_degree"</span>, <span class="st">"log_median_inc"</span>, <span class="st">"log_pop_denc"</span>),</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">new =</span> <span class="fu">c</span>(<span class="st">"Home Value (log)"</span>, <span class="st">"Percent University Degree"</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Median Income (log)"</span>, <span class="st">"Population Density (log)"</span>))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Love plot</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="fu">love.plot</span>(match_model, <span class="at">stats =</span> <span class="st">"mean.diffs"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">thresholds =</span> <span class="fu">c</span>(<span class="at">m =</span> <span class="fl">0.1</span>),</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">var.names =</span> new_names)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW2_START_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>2D.Q1</strong> Interpret the love plot in your own words:</p>
<p><em>Response:</em> _________________________</p>
<p>The love plot shows the standardized mean differences between the control and treatment of our covariates decreased significantly after we matched treatments to their closest counterfactual.</p>
<hr>
</section>
</section>
<section id="propensity-score-matching" class="level3">
<h3 class="anchored" data-anchor-id="propensity-score-matching">Propensity score matching</h3>
<hr>
<section id="e.-propensity-score-matching-psm" class="level4">
<h4 class="anchored" data-anchor-id="e.-propensity-score-matching-psm">2E. Propensity Score Matching (PSM)</h4>
<ul>
<li>Estimate 1:1 nearest-neighbor Propensity Score Matching</li>
<li>Same code as above except change <code>distance = "logit"</code></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2412026</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>propensity_scores <span class="ot">&lt;-</span> <span class="fu">matchit</span>(proposed_turbine_3km <span class="sc">~</span> log_home_val_07 <span class="sc">+</span> </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    p_uni_degree <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    log_median_inc <span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    log_pop_denc,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> match_data, </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"nearest"</span>,       <span class="co"># Nearest neighbor matching</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">distance =</span> <span class="st">"logit"</span>,       <span class="co"># logit distance</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">ratio =</span> <span class="dv">1</span>,                <span class="co"># Match one control unit to one treatment unit (1:1 matching)</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">replace =</span> <span class="cn">FALSE</span>           <span class="co"># Control observations are not replaced</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<hr>
</section>
<section id="create-table-displaying-covariate-balance-using-cobaltbal.tab" class="level4">
<h4 class="anchored" data-anchor-id="create-table-displaying-covariate-balance-using-cobaltbal.tab">Create table displaying covariate balance using <code>cobalt::bal.tab()</code></h4>
<p>📜 <a href="https://ngreifer.github.io/cobalt/">Documentation - cobalt</a></p>
<p>Use <code>bal.tab()</code> to report balance before and after matching.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bal.tab</span>(propensity_scores, </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">un =</span> <span class="cn">TRUE</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">var.names =</span> new_names) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Balance Measures
                    Type Diff.Un Diff.Adj
distance        Distance  0.7248   0.0001
log_home_val_07  Contin.  0.1138   0.0205
p_uni_degree     Contin. -0.5032   0.0457
log_median_inc   Contin. -0.0636  -0.0042
log_pop_denc     Contin. -0.8897  -0.0365

Sample sizes
          Control Treated
All          5619     354
Matched       354     354
Unmatched    5265       0</code></pre>
</div>
</div>
<p><strong>2E.Q1</strong> Compare Mahalanobis vs propensity score matching. Which method did a better job at achieving balance?</p>
<p><em>Response:</em> _________________________</p>
<p>Mahalanobis had a smaller standard mean difference across all covariates. Because of this, Mahalanobis did a better job at achieving balance.</p>
<hr>
</section>
<section id="f.-estimate-an-effect-in-the-matched-sample" class="level4">
<h4 class="anchored" data-anchor-id="f.-estimate-an-effect-in-the-matched-sample">2F. Estimate an effect in the matched sample</h4>
<p>Using the matched data (Mahalanobis method), estimate the effect of treatment on the change in incumbent vote share (<code>change_liberal</code>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>reg_match <span class="ot">&lt;-</span> <span class="fu">lm</span>(change_liberal <span class="sc">~</span> proposed_turbine_3km,</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> matched_data,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">weights =</span> weights)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(reg_match, <span class="at">model.fit =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Observations</td>
<td style="text-align: right;">708</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Dependent variable</td>
<td style="text-align: right;">change_liberal</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Type</td>
<td style="text-align: right;">OLS linear regression</td>
</tr>
</tbody>
</table>
</div>
  
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Est.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">S.E.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t val.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">(Intercept)</td>
<td style="text-align: right;">-0.07</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">-10.96</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">proposed_turbine_3km</td>
<td style="text-align: right;">-0.06</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">-7.25</td>
<td style="text-align: right;">0.00</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> Standard errors: OLS</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</div>
<p><strong>2F.Q1</strong> Have you identified a causal estimate using this approach: Why or why not?</p>
<p><em>Response:</em> _________________________</p>
<p>Assumption that I have balanced relevant confounding variables, I have found a causal estimate using this approach. Since I matched treatment groups to their closest control match, this minimized group differences that are not due to proximity to wind turbines. This isolated the effect of proximity to wind turbines. The coefficient for this variable was found to be statistically significant coefficient, suggesting proximity to turbines is associated with a 6% decline in Liberal vote share.</p>
<p><strong>2F.Q2</strong> When using a matching method, what is the main threat to causal identification?</p>
<p><em>Response:</em> _________________________</p>
<p>The main threat is that matching alone does not address potential selection bias coming from variables that were not observed.</p>
<p><strong>2F.Q3</strong> Describe why the treatment estimate represents the <code>Average Treatment for the Treated (ATT)</code> and explain why this is the case relative to estimation of the <code>Average Treatment Effect (ATE)</code>.</p>
<p><em>Response:</em> _________________________</p>
<p>It represents the ATT because the treatment estimate comes from the effect of the treatment on the 354 treated precincts relative to the matched 354 control precincts - not the full sample of over 5,000 control precincts. This means we’re only estimating the effect of turbines on precincts for 354 matched groups. If we had estimated the effect of this treatment on all the precinct in our model this would have given us ATE.</p>
<hr>
</section>
</section>
<section id="part-3-panel-data-fixed-effects-and-difference-in-difference" class="level3">
<h3 class="anchored" data-anchor-id="part-3-panel-data-fixed-effects-and-difference-in-difference">Part 3: Panel Data, Fixed Effects, and Difference-in-Difference</h3>
<p><strong>Data source:</strong> <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/SDUGCC">Dataverse-Stokes2015</a></p>
<hr>
<section id="a-read-in-the-panel-data-code-variables-precinct_id-and-year-as-factors" class="level4">
<h4 class="anchored" data-anchor-id="a-read-in-the-panel-data-code-variables-precinct_id-and-year-as-factors"><strong>3A:</strong> Read in the panel data + code variables <code>precinct_id</code> and <code>year</code> as factors</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>panel_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"Stokes15_panel_data.csv"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">precinct_id =</span> <span class="fu">as.factor</span>(precinct_id),</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">year =</span> <span class="fu">as.factor</span>(year))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># HINT: Try running `tabyl(panel_data$year)`. Review article to make sense of the row numbers (n).</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(panel_data<span class="sc">$</span>year)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> panel_data$year    n   percent
            2003 6186 0.3333333
            2007 6186 0.3333333
            2011 6186 0.3333333</code></pre>
</div>
</div>
<p><strong>3A.Q1:</strong> Why are there 18,558 rows in <code>panel_data</code>?</p>
<p><em>Response:</em> _________________________</p>
<p>There were 18,558 rows in panel_data because there are 6186 precincts and this data is collected once a year across three years. 18,558 is simply the result of 6186 three times.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># How many years are included in the panel?</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># How many precincts are there? </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>3A.Q2:</strong> How many unique precincts are <em>ever treated</em> (i.e., <code>proposed</code> &amp; <code>operational</code>)?</p>
<p><em>Response:</em> _________________________</p>
<p>There are 184 unique precincts ever treated in the proposed category and 52 unique precincts ever treated in the operational category.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>panel_data <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(precinct_id) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">ever_proposed    =</span> <span class="fu">any</span>(proposed_turbine <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">ever_operational =</span> <span class="fu">any</span>(operational_turbine <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_ever_proposed    =</span> <span class="fu">sum</span>(ever_proposed),</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_ever_operational =</span> <span class="fu">sum</span>(ever_operational))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  n_ever_proposed n_ever_operational
            &lt;int&gt;              &lt;int&gt;
1             184                 52</code></pre>
</div>
</div>
<hr>
</section>
<section id="b.-plot-and-evaluate-parallel-trends-replicate-figure.2-stokes-2015" class="level4">
<h4 class="anchored" data-anchor-id="b.-plot-and-evaluate-parallel-trends-replicate-figure.2-stokes-2015"><strong>3B.</strong> Plot and evaluate parallel trends: Replicate <code>Figure.2</code> (Stokes, 2015)</h4>
<ol type="1">
<li>Create indicators for whether each precinct is ever treated by 2011 (<code>treat_p</code>, <code>treat_o</code>; separate indicator for proposals and operational turbines).</li>
<li>Plot mean incumbent vote share by year for treated vs control precincts (with 95% CIs).</li>
<li>Facet by turbine type (proposed &amp; operational)</li>
</ol>
<p>Step 1: Prepare data</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>trends_data <span class="ot">&lt;-</span> panel_data <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(precinct_id) <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">treat_p =</span> <span class="fu">as.integer</span>(<span class="fu">any</span>(proposed_turbine <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),  <span class="co"># ever proposed (in any year)</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">treat_o =</span> <span class="fu">as.integer</span>(<span class="fu">any</span>(operational_turbine <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))) <span class="sc">%&gt;%</span> <span class="co"># ever operational (in any year)</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">c</span>(treat_p, treat_o),</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"turbine_type"</span>, <span class="at">values_to =</span> <span class="st">"treat"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">turbine_type =</span> <span class="fu">factor</span>(turbine_type,</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>                            <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"treat_p"</span>, <span class="st">"treat_o"</span>),</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Proposed turbines"</span>, <span class="st">"Operational turbines"</span>)),  </span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">status =</span> <span class="fu">if_else</span>(treat <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Treated"</span>, <span class="st">"Control"</span>),</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">year   =</span> <span class="fu">factor</span>(year))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Step 2: Create trends plot</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>pd <span class="ot">&lt;-</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.15</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>trends_data <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(turbine_type, status, year) <span class="sc">%&gt;%</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(perc_lib, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">n    =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(perc_lib)),</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">se   =</span> <span class="fu">sd</span>(perc_lib, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(n), </span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">ci   =</span> <span class="fu">qt</span>(.<span class="dv">975</span>, <span class="at">df =</span> <span class="fu">pmax</span>(n <span class="sc">-</span> <span class="dv">1</span>, <span class="dv">1</span>)) <span class="sc">*</span> se,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(year, mean, <span class="at">color =</span> status, <span class="at">group =</span> status)) <span class="sc">+</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">position =</span> pd, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position =</span> pd, <span class="at">size =</span> <span class="fl">2.6</span>) <span class="sc">+</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">ymin =</span> mean <span class="sc">-</span> ci, <span class="at">ymax =</span> mean <span class="sc">+</span> ci),</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">position =</span> pd, <span class="at">width =</span> .<span class="dv">12</span>, <span class="at">linewidth =</span> .<span class="dv">7</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> turbine_type, <span class="at">nrow =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="at">Control =</span> <span class="st">"#0072B2"</span>, <span class="at">Treated =</span> <span class="st">"#B22222"</span>)) <span class="sc">+</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="fu">percent_format</span>(<span class="at">accuracy =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(.<span class="dv">20</span>, .<span class="dv">57</span>)) <span class="sc">+</span></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Figure 2. Trends in the Governing Party’s Vote Share"</span>,</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Election Year"</span>,</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Liberal Party Vote Share"</span>,</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW2_START_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>3B.Q1:</strong> Write a short paragraph assessing the parallel trends assumption for each outcome.</p>
<p><em>Response (4-6 sentences):</em> _________________________</p>
<hr>
<p>For the proposed turbines group, the parallel trends assumption seems well satisfied. The pre-treatment period for the control and treatment groups seem to match up well and the treated group seems to experience a decline following the introduction of the turbine proposal. For the operational turbines group, the parallel trends assumption is not satisfied as well. During the pre-treatment period for the control and treatment groups, it seems that the treated group starts at a higher initial liberal party vote share than the control group. Regardless, we also see a decline following the introduction of the turbine proposal for operational turbine precincts.</p>
</section>
</section>
<section id="estimating-fixed-effects-models-did-for-proposals" class="level3">
<h3 class="anchored" data-anchor-id="estimating-fixed-effects-models-did-for-proposals">Estimating Fixed Effects Models (DiD) for proposals</h3>
<p><span class="math display">\[
\text{Y}_{it}
=  \alpha_0 +
\beta \cdot (\text{proposed_turbine}_{it})
+ \gamma_i
+ \delta_t
+ \varepsilon_{it}
\]</span></p>
<ul>
<li><span class="math inline">\(Y_{it}\)</span> is the vote share for the Liberal Party in precinct <em>i</em> in time <em>t</em></li>
<li><span class="math inline">\(\beta\)</span> is the treatment effect of a turbine being proposed within a precinct</li>
<li><span class="math inline">\(\gamma_i\)</span> is the precinct fixed effect</li>
<li><span class="math inline">\(\delta_t\)</span> is the year fixed effect</li>
</ul>
<hr>
</section>
<section id="example-1-randomly-sample-40-precincts" class="level3">
<h3 class="anchored" data-anchor-id="example-1-randomly-sample-40-precincts">Example 1: Randomly sample 40 precincts</h3>
<ul>
<li>To illustrate the “dummy variable method” of estimating fixed effects using the the general <code>lm()</code> function we are going to randomly sample 40 precincts (20 “treated” precincts with proposed turbines).</li>
<li>If we attempted to use this approach with the full sample estimating all 6185 (n-1) precinct-level coefficients is impractical (it would take a long time).</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">40002026</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>precinct_frame <span class="ot">&lt;-</span> panel_data <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(precinct_id) <span class="sc">%&gt;%</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">proposed_turbine_any =</span> <span class="fu">as.integer</span>(<span class="fu">any</span>(proposed_turbine <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>ids_40 <span class="ot">&lt;-</span> precinct_frame <span class="sc">%&gt;%</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(proposed_turbine_any) <span class="sc">%&gt;%</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">20</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(precinct_id)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>sample_40_precincts <span class="ot">&lt;-</span> panel_data <span class="sc">%&gt;%</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">semi_join</span>(ids_40, <span class="at">by =</span> <span class="st">"precinct_id"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<hr>
<section id="c-estimate-a-fixed-effects-model-using-lm-with-fixed-effects-added-for-precinct-and-year-using-the-sample-of-40-precincts-just-created." class="level4">
<h4 class="anchored" data-anchor-id="c-estimate-a-fixed-effects-model-using-lm-with-fixed-effects-added-for-precinct-and-year-using-the-sample-of-40-precincts-just-created."><strong>3C:</strong> Estimate a fixed effects model using <code>lm()</code> with fixed effects added for <code>precinct</code> and <code>year</code> using the sample of 40 precincts just created.</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>model1_ff <span class="ot">&lt;-</span> <span class="fu">lm</span>(perc_lib <span class="sc">~</span> proposed_turbine <span class="sc">+</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                   precinct_id <span class="sc">+</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                   year,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> sample_40_precincts)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(model1_ff , <span class="at">model.fit =</span> <span class="cn">FALSE</span>, <span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Observations</td>
<td style="text-align: right;">120</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Dependent variable</td>
<td style="text-align: right;">perc_lib</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Type</td>
<td style="text-align: right;">OLS linear regression</td>
</tr>
</tbody>
</table>
</div>
  
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Est.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">S.E.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t val.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">(Intercept)</td>
<td style="text-align: right;">0.275</td>
<td style="text-align: right;">0.050</td>
<td style="text-align: right;">5.460</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">proposed_turbine</td>
<td style="text-align: right;">-0.057</td>
<td style="text-align: right;">0.031</td>
<td style="text-align: right;">-1.858</td>
<td style="text-align: right;">0.067</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id10.115s.10.84.</td>
<td style="text-align: right;">0.166</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">2.402</td>
<td style="text-align: right;">0.019</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id105.038.105.45.</td>
<td style="text-align: right;">0.053</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">0.765</td>
<td style="text-align: right;">0.447</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id14.149.14.79.</td>
<td style="text-align: right;">0.208</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">2.976</td>
<td style="text-align: right;">0.004</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id14.168.14.82.</td>
<td style="text-align: right;">0.192</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">2.749</td>
<td style="text-align: right;">0.007</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id18.003.18.1.</td>
<td style="text-align: right;">0.121</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">1.738</td>
<td style="text-align: right;">0.086</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id18.033.18.19.</td>
<td style="text-align: right;">-0.002</td>
<td style="text-align: right;">0.072</td>
<td style="text-align: right;">-0.034</td>
<td style="text-align: right;">0.973</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id21.126.21.179.</td>
<td style="text-align: right;">0.204</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">2.950</td>
<td style="text-align: right;">0.004</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id22.061.22.60.</td>
<td style="text-align: right;">0.213</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">3.047</td>
<td style="text-align: right;">0.003</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id22.124.22.52.</td>
<td style="text-align: right;">0.156</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">2.230</td>
<td style="text-align: right;">0.029</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id22.137.22.193.</td>
<td style="text-align: right;">0.179</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">2.590</td>
<td style="text-align: right;">0.011</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id22.158.22.203.</td>
<td style="text-align: right;">0.165</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">2.357</td>
<td style="text-align: right;">0.021</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id22.209.22.172.</td>
<td style="text-align: right;">0.188</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">2.699</td>
<td style="text-align: right;">0.009</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id28.056.28.149.</td>
<td style="text-align: right;">-0.011</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">-0.160</td>
<td style="text-align: right;">0.873</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id28.072.28.98.</td>
<td style="text-align: right;">0.097</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">1.409</td>
<td style="text-align: right;">0.163</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id28.139.28.145.</td>
<td style="text-align: right;">0.040</td>
<td style="text-align: right;">0.072</td>
<td style="text-align: right;">0.553</td>
<td style="text-align: right;">0.582</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id28.163.28.69.</td>
<td style="text-align: right;">0.124</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">1.802</td>
<td style="text-align: right;">0.075</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id29.241.29.172.</td>
<td style="text-align: right;">0.067</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">0.958</td>
<td style="text-align: right;">0.341</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id34.050.34.39.</td>
<td style="text-align: right;">0.342</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">4.947</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id34.151.34.125.</td>
<td style="text-align: right;">0.098</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">1.399</td>
<td style="text-align: right;">0.166</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id36.133.36.92.</td>
<td style="text-align: right;">0.358</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">5.179</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id40.044.40.68.</td>
<td style="text-align: right;">0.236</td>
<td style="text-align: right;">0.072</td>
<td style="text-align: right;">3.275</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id40.098.40.120.</td>
<td style="text-align: right;">0.195</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">2.792</td>
<td style="text-align: right;">0.007</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id40.134.40.174.</td>
<td style="text-align: right;">0.216</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">3.127</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id40.243.40.22.</td>
<td style="text-align: right;">0.325</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">4.651</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id40.244.40.46.</td>
<td style="text-align: right;">0.178</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">2.543</td>
<td style="text-align: right;">0.013</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id55.228.55.180.</td>
<td style="text-align: right;">0.130</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">1.883</td>
<td style="text-align: right;">0.064</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id58.162.58.98.</td>
<td style="text-align: right;">0.278</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">4.024</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id58.232.58.231.</td>
<td style="text-align: right;">0.203</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">2.940</td>
<td style="text-align: right;">0.004</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id67.141.67.123.</td>
<td style="text-align: right;">0.022</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">0.311</td>
<td style="text-align: right;">0.757</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id69.073.69.35.</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">1.015</td>
<td style="text-align: right;">0.313</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id70.081.70.44.</td>
<td style="text-align: right;">0.062</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">0.899</td>
<td style="text-align: right;">0.372</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id70.135.70.105.</td>
<td style="text-align: right;">0.441</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">6.388</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id70.221.70.155.</td>
<td style="text-align: right;">0.247</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">3.576</td>
<td style="text-align: right;">0.001</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id73.248.73.180.</td>
<td style="text-align: right;">0.187</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">2.672</td>
<td style="text-align: right;">0.009</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id73.251.73.180.</td>
<td style="text-align: right;">0.204</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">2.927</td>
<td style="text-align: right;">0.005</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id87.017.87.58.</td>
<td style="text-align: right;">0.127</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">1.836</td>
<td style="text-align: right;">0.070</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id87.053.87.68.</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">3.100</td>
<td style="text-align: right;">0.003</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id87.213.87.24.</td>
<td style="text-align: right;">0.033</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">0.469</td>
<td style="text-align: right;">0.641</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id98.009.98.12.</td>
<td style="text-align: right;">0.129</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">1.868</td>
<td style="text-align: right;">0.066</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">year2007</td>
<td style="text-align: right;">-0.045</td>
<td style="text-align: right;">0.019</td>
<td style="text-align: right;">-2.364</td>
<td style="text-align: right;">0.021</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">year2011</td>
<td style="text-align: right;">-0.131</td>
<td style="text-align: right;">0.024</td>
<td style="text-align: right;">-5.381</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> Standard errors: OLS</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</div>
<p><strong>3C.Q1:</strong> Intuition check: Is the <em>signal-to-noise</em> ratio for the treatment estimate greater than <em>2-to-1</em>?</p>
<p><em>Response:</em> _________________________</p>
<blockquote class="blockquote">
<p>HINT: Add the argument <code>digits = 3</code> to the <code>summ()</code> function above</p>
<p>No, the signal-to-noise ratio for the treatment estimate is not greater than 2 - 1. It is not significant.</p>
</blockquote>
<p><strong>3C.Q2:</strong> Re-run the <code>summ()</code> function using the <em>heteroscedasticiy robust standard error adjustment</em> (<code>robust = TRUE</code>). Did the standard error (S.E.) estimates change? Explain why.</p>
<p><em>Response:</em> _________________________</p>
<p>Yes the standard error became larger. This is because using the <em>heteroscedasticiy robust standard error adjustment</em> allows for variance in the standard error across observations. This causes more variation in standard errors than the previous calculation which assumed a constant variance.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(model1_ff , <span class="at">model.fit =</span> <span class="cn">FALSE</span>, <span class="at">digits =</span> <span class="dv">3</span>, <span class="at">robust =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Observations</td>
<td style="text-align: right;">120</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Dependent variable</td>
<td style="text-align: right;">perc_lib</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Type</td>
<td style="text-align: right;">OLS linear regression</td>
</tr>
</tbody>
</table>
</div>
  
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Est.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">S.E.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t val.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">(Intercept)</td>
<td style="text-align: right;">0.275</td>
<td style="text-align: right;">0.085</td>
<td style="text-align: right;">3.247</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">proposed_turbine</td>
<td style="text-align: right;">-0.057</td>
<td style="text-align: right;">0.039</td>
<td style="text-align: right;">-1.465</td>
<td style="text-align: right;">0.147</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id10.115s.10.84.</td>
<td style="text-align: right;">0.166</td>
<td style="text-align: right;">0.101</td>
<td style="text-align: right;">1.646</td>
<td style="text-align: right;">0.104</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id105.038.105.45.</td>
<td style="text-align: right;">0.053</td>
<td style="text-align: right;">0.104</td>
<td style="text-align: right;">0.509</td>
<td style="text-align: right;">0.612</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id14.149.14.79.</td>
<td style="text-align: right;">0.208</td>
<td style="text-align: right;">0.094</td>
<td style="text-align: right;">2.201</td>
<td style="text-align: right;">0.031</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id14.168.14.82.</td>
<td style="text-align: right;">0.192</td>
<td style="text-align: right;">0.110</td>
<td style="text-align: right;">1.751</td>
<td style="text-align: right;">0.084</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id18.003.18.1.</td>
<td style="text-align: right;">0.121</td>
<td style="text-align: right;">0.107</td>
<td style="text-align: right;">1.132</td>
<td style="text-align: right;">0.261</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id18.033.18.19.</td>
<td style="text-align: right;">-0.002</td>
<td style="text-align: right;">0.101</td>
<td style="text-align: right;">-0.024</td>
<td style="text-align: right;">0.981</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id21.126.21.179.</td>
<td style="text-align: right;">0.204</td>
<td style="text-align: right;">0.157</td>
<td style="text-align: right;">1.299</td>
<td style="text-align: right;">0.198</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id22.061.22.60.</td>
<td style="text-align: right;">0.213</td>
<td style="text-align: right;">0.105</td>
<td style="text-align: right;">2.023</td>
<td style="text-align: right;">0.047</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id22.124.22.52.</td>
<td style="text-align: right;">0.156</td>
<td style="text-align: right;">0.103</td>
<td style="text-align: right;">1.509</td>
<td style="text-align: right;">0.135</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id22.137.22.193.</td>
<td style="text-align: right;">0.179</td>
<td style="text-align: right;">0.104</td>
<td style="text-align: right;">1.721</td>
<td style="text-align: right;">0.089</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id22.158.22.203.</td>
<td style="text-align: right;">0.165</td>
<td style="text-align: right;">0.088</td>
<td style="text-align: right;">1.879</td>
<td style="text-align: right;">0.064</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id22.209.22.172.</td>
<td style="text-align: right;">0.188</td>
<td style="text-align: right;">0.106</td>
<td style="text-align: right;">1.770</td>
<td style="text-align: right;">0.081</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id28.056.28.149.</td>
<td style="text-align: right;">-0.011</td>
<td style="text-align: right;">0.112</td>
<td style="text-align: right;">-0.099</td>
<td style="text-align: right;">0.921</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id28.072.28.98.</td>
<td style="text-align: right;">0.097</td>
<td style="text-align: right;">0.104</td>
<td style="text-align: right;">0.934</td>
<td style="text-align: right;">0.353</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id28.139.28.145.</td>
<td style="text-align: right;">0.040</td>
<td style="text-align: right;">0.111</td>
<td style="text-align: right;">0.359</td>
<td style="text-align: right;">0.721</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id28.163.28.69.</td>
<td style="text-align: right;">0.124</td>
<td style="text-align: right;">0.106</td>
<td style="text-align: right;">1.179</td>
<td style="text-align: right;">0.242</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id29.241.29.172.</td>
<td style="text-align: right;">0.067</td>
<td style="text-align: right;">0.089</td>
<td style="text-align: right;">0.749</td>
<td style="text-align: right;">0.456</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id34.050.34.39.</td>
<td style="text-align: right;">0.342</td>
<td style="text-align: right;">0.089</td>
<td style="text-align: right;">3.821</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id34.151.34.125.</td>
<td style="text-align: right;">0.098</td>
<td style="text-align: right;">0.093</td>
<td style="text-align: right;">1.050</td>
<td style="text-align: right;">0.297</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id36.133.36.92.</td>
<td style="text-align: right;">0.358</td>
<td style="text-align: right;">0.091</td>
<td style="text-align: right;">3.941</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id40.044.40.68.</td>
<td style="text-align: right;">0.236</td>
<td style="text-align: right;">0.096</td>
<td style="text-align: right;">2.457</td>
<td style="text-align: right;">0.016</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id40.098.40.120.</td>
<td style="text-align: right;">0.195</td>
<td style="text-align: right;">0.092</td>
<td style="text-align: right;">2.123</td>
<td style="text-align: right;">0.037</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id40.134.40.174.</td>
<td style="text-align: right;">0.216</td>
<td style="text-align: right;">0.090</td>
<td style="text-align: right;">2.399</td>
<td style="text-align: right;">0.019</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id40.243.40.22.</td>
<td style="text-align: right;">0.325</td>
<td style="text-align: right;">0.098</td>
<td style="text-align: right;">3.314</td>
<td style="text-align: right;">0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id40.244.40.46.</td>
<td style="text-align: right;">0.178</td>
<td style="text-align: right;">0.095</td>
<td style="text-align: right;">1.873</td>
<td style="text-align: right;">0.065</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id55.228.55.180.</td>
<td style="text-align: right;">0.130</td>
<td style="text-align: right;">0.092</td>
<td style="text-align: right;">1.406</td>
<td style="text-align: right;">0.164</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id58.162.58.98.</td>
<td style="text-align: right;">0.278</td>
<td style="text-align: right;">0.097</td>
<td style="text-align: right;">2.867</td>
<td style="text-align: right;">0.005</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id58.232.58.231.</td>
<td style="text-align: right;">0.203</td>
<td style="text-align: right;">0.092</td>
<td style="text-align: right;">2.203</td>
<td style="text-align: right;">0.031</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id67.141.67.123.</td>
<td style="text-align: right;">0.022</td>
<td style="text-align: right;">0.115</td>
<td style="text-align: right;">0.189</td>
<td style="text-align: right;">0.850</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id69.073.69.35.</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">0.104</td>
<td style="text-align: right;">0.677</td>
<td style="text-align: right;">0.500</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id70.081.70.44.</td>
<td style="text-align: right;">0.062</td>
<td style="text-align: right;">0.095</td>
<td style="text-align: right;">0.655</td>
<td style="text-align: right;">0.514</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id70.135.70.105.</td>
<td style="text-align: right;">0.441</td>
<td style="text-align: right;">0.128</td>
<td style="text-align: right;">3.451</td>
<td style="text-align: right;">0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id70.221.70.155.</td>
<td style="text-align: right;">0.247</td>
<td style="text-align: right;">0.111</td>
<td style="text-align: right;">2.217</td>
<td style="text-align: right;">0.030</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id73.248.73.180.</td>
<td style="text-align: right;">0.187</td>
<td style="text-align: right;">0.108</td>
<td style="text-align: right;">1.720</td>
<td style="text-align: right;">0.089</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id73.251.73.180.</td>
<td style="text-align: right;">0.204</td>
<td style="text-align: right;">0.102</td>
<td style="text-align: right;">1.995</td>
<td style="text-align: right;">0.050</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id87.017.87.58.</td>
<td style="text-align: right;">0.127</td>
<td style="text-align: right;">0.112</td>
<td style="text-align: right;">1.135</td>
<td style="text-align: right;">0.260</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id87.053.87.68.</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">0.150</td>
<td style="text-align: right;">1.428</td>
<td style="text-align: right;">0.157</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id87.213.87.24.</td>
<td style="text-align: right;">0.033</td>
<td style="text-align: right;">0.087</td>
<td style="text-align: right;">0.375</td>
<td style="text-align: right;">0.709</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id98.009.98.12.</td>
<td style="text-align: right;">0.129</td>
<td style="text-align: right;">0.107</td>
<td style="text-align: right;">1.210</td>
<td style="text-align: right;">0.230</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">year2007</td>
<td style="text-align: right;">-0.045</td>
<td style="text-align: right;">0.024</td>
<td style="text-align: right;">-1.876</td>
<td style="text-align: right;">0.064</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">year2011</td>
<td style="text-align: right;">-0.131</td>
<td style="text-align: right;">0.036</td>
<td style="text-align: right;">-3.686</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> Standard errors: Robust, type = HC3</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</div>
<p><strong>3C.Q3:</strong> Compare results of the model above to the findings from the fixed effects analysis in the Stokes (2015) study. Why might the results be similar or different?</p>
<p><em>Response:</em> _________________________</p>
<p>The model above estimates the average effect of having a proposed wind turbine to be go down by 5.7%. The findings from the fixed effects analysis, on the other hand, show this to be a decrease of about 4%. Results could be different because I accounted for variance in standard error in my model and this caused large differences in this percentage.</p>
<p><strong>3C.Q4:</strong> In your own words, explain why it is advantageous from a causal inference perspective to include year and precinct fixed effects. Explain how between-level and within-level variance is relevant to the problem of omitted variable bias (OVB).</p>
<p><em>Response (2-4 sentences):</em> _________________________</p>
<hr>
<p>Including year and precinct fixed effects is advantageous because including year absorbs common shocks shared by all precincts in a given year. Including precinct fixed effects absorbs time-invariant differences across precincts. By focusing on within-level variance this model reduced OVB that could potentially happen if you failed to measure a confounding variable.</p>
</section>
<section id="d.-now-using-the-full-sample-estimate-the-treatment-effect-of-wind-turbine-proposals-on-incumbent-vote-share.-use-feols-from-the-fixest-package-to-estimate-the-fixed-effects." class="level4">
<h4 class="anchored" data-anchor-id="d.-now-using-the-full-sample-estimate-the-treatment-effect-of-wind-turbine-proposals-on-incumbent-vote-share.-use-feols-from-the-fixest-package-to-estimate-the-fixed-effects."><strong>3D.</strong> Now using the full sample, estimate the treatment effect of wind turbine proposals on incumbent vote share. Use <code>feols()</code> from the <code>{fixest}</code> package to estimate the fixed effects.</h4>
<p>See vignette here: <a href="https://cran.r-project.org/web/packages/fixest/vignettes/fixest_walkthrough.html#11_Estimation">fixest walkthrough</a></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>model2_ff <span class="ot">&lt;-</span> <span class="fu">feols</span>(</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  perc_lib <span class="sc">~</span> proposed_turbine <span class="sc">|</span> precinct_id <span class="sc">+</span> year,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> panel_data, </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">cluster =</span> <span class="sc">~</span> precinct_id</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2_ff)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: perc_lib
Observations: 18,558
Fixed-effects: precinct_id: 6,186,  year: 3
Standard-errors: Clustered (precinct_id) 
                 Estimate Std. Error  t value   Pr(&gt;|t|)    
proposed_turbine -0.04157   0.007682 -5.41144 6.4869e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.070481     Adj. R2: 0.624835
                 Within R2: 0.00224 </code></pre>
</div>
</div>
<p><strong>3D.Q1:</strong> Interpret the model results and translate findings to be clear to an audience that may not have a background in causal inference (Econometrics) methods.</p>
<p>In panel data settings, why is clustering by precinct important (i.e., <code>cluster = ~precinct_id</code>) ?”</p>
<p><em>Response (4-6 sentences):</em> _________________________</p>
<p>The model states that there is about a -4% decrease in liberal voter shares near a proposed wind turbine. This coefficient is statistically significant. This means there is evidence to support the notion that proposed wind turbines caused people in those precincts to punish incumbents by decreasing their share of liberal votes. Clustering is important because it addresses the fact that vote outcomes from one election might influence vote outcomes for that same precinct for future elections. Clustering ensures the model doesn’t underestimate uncertainty.</p>
<hr>
</section>
<section id="e.-estimate-the-treatment-effect-of-operational-wind-turbines-on-incumbent-vote-share.-use-the-same-approach-as-the-previous-model." class="level4">
<h4 class="anchored" data-anchor-id="e.-estimate-the-treatment-effect-of-operational-wind-turbines-on-incumbent-vote-share.-use-the-same-approach-as-the-previous-model."><strong>3E.</strong> Estimate the treatment effect of <em>operational wind turbines</em> on incumbent vote share. Use the same approach as the previous model.</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>model3_ff <span class="ot">&lt;-</span> <span class="fu">feols</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  perc_lib <span class="sc">~</span> operational_turbine <span class="sc">|</span> precinct_id <span class="sc">+</span> year,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> panel_data, </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">cluster =</span> <span class="sc">~</span> precinct_id</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3_ff)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: perc_lib
Observations: 18,558
Fixed-effects: precinct_id: 6,186,  year: 3
Standard-errors: Clustered (precinct_id) 
                     Estimate Std. Error  t value   Pr(&gt;|t|)    
operational_turbine -0.092762   0.011739 -7.90195 3.2271e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.070447     Adj. R2: 0.625198
                 Within R2: 0.003206</code></pre>
</div>
</div>
<p><strong>3E.Q1:</strong> Interpret the <code>model3_ff</code> results as clearly and <strong>concisely</strong> as you can.</p>
<p><em>Response:</em> _________________________</p>
<p>The model states that there is a statistically significant 9% decrease in liberal voter shares within the same precinct over time when a wind turbine operates in their precinct. This provides evidence for people in precincts near operational wind turbines decreasing their share of liberal votes.</p>
<p><strong>3E.Q2:</strong> Why do you think the effect of proposed wind turbines is different from operational wind turbines. Develop your own theory about why incumbent vote share is affected in this way. Use the Stokes (2015) study to inform your response as needed.</p>
<p><em>Response:</em> _________________________</p>
<p>I think the effect of operational wind turbines is greater than the effect of proposed wind turbines because people living near these wind turbines wont fell as impacted by hearing about proposed wind turbines as they will with physically seeing and dealing with them. Additionally, since developers didn’t need local approval a lot of people living near these wind turbines might not have even known a wind turbine was getting built until they physically saw it - so they couldn’t oppose it before.</p>
<hr>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>